### ISSUE TITLE
help: How to choose the right blobstore type in different cases?

### ISSUE THREAD

**Issue by keyu98** [facebookexperimental/eden#112]
Thanks for the recent commits, which allowed me to build the code success.

I am very interested in the mononoke in the project, so I have invested in the research of this part of the code.

While reading the code, I found that mononoke provides many types of blobstores, including files, sql, s3, etc. And I have some questions about it:

1. I saw a type called **Manifold**, but I didn't find any information about it on the internet (I guess it may be a k-v storage).  Could you tell me what it is used for?
2. Of course, it would be great if there is documentation about **blobstore.toml** config.

**Comment by ahornby** [comment]
For the purposes of Mononoke manifold acts as a large scale blobstore, similar in purpose to S3
