### ISSUE TITLE
osxfuse 4.0 issue

### ISSUE THREAD

**Issue by jarrocha** [facebookexperimental/eden#69]
Hello guys,
I saw your post here: https://github.com/osxfuse/osxfuse/issues/742
Though I encourage support for the closed source project, this is a API that could soon reach complete blockage from Apple, I wanted to let you know that I can help you compile a previous "open source" version (3.8.3) of osxfuse for macOS 11.

Many people are having issues due to the lack of proper documentation.

**Comment by xavierd** [comment]
A bit delayed, and thanks for your proposed help!

EdenFS is however moving away from using osxfuse/macfuse entirely and instead relying on a loopback NFS server  (https://github.com/facebookexperimental/eden/tree/master/eden/fs/nfs) on macOS.
