### ISSUE TITLE
OSS Help

### ISSUE THREAD

**Issue by dymart** [facebookexperimental/eden#90]
Hi, really like the project!

I would be interested in helping to get the oss version of this to build and run. 

Wanted to check and see if maintainers would be open to reviewing and maybe providing direction on prs and changes.
Also wanted to check and see if it will be feasible to get an oss version of this working or if there are internal blockers to this happening (ex: key dependencies that are not open source yet and no workaround is desired).

 hopeful to see an oss version of this running!

**Comment by chadaustin** [comment]
We would accept PRs! There are no internal blockers or key dependencies, but there might be a few dependencies that only have stub implementations. There are three components here: EdenFS, EdenSCM, and Mononoke. They could probably be made to work in open source builds independently, and we can provide some review and guidance depending on what you're most interested in starting with. :)

**Comment by dymart** [comment]
Hi Chad,
That is great to hear!!
I will probably start with EdenFS as I've been able to build that with some changes so finding the best way to upstream those could be a good staring point.
I'll break the changes down into small pieces to allow for easier discussion/acceptance, my intention is not to spam changes but just to make review and proposed changes easier for everyone.

**Comment by ahornby** [comment]
Current state:  The OSS build completes now for Eden CLI build and test, Mononoke build and test and Eden FS build. README.md is updated with build steps using getdeps.py to coordinate.  EdenFS tests hang about half way through when I run them on github actions, probably due to config missing that is present on our internal hosts.

**Comment by dymart** [comment]
@ahornby thank you for updating the OSS build and updating the readme along with @genevievehelsel !!
